# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  release:
    cmds:
      - gh release create index packages/**/*.whl packages/**/*.metadata packages/**/*.tar.gz
